### ISSUE TITLE
Crashes on Android 5.1.1. RecyclerView doesn't work correctly?

### ISSUE THREAD

**Issue by Crylion** [Kennyc1012/Opengur#118]
App crashes for me consistently when trying to open any post from the list/gallery. Logcat reports:

    Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$LayoutManager.canScrollVertically()' on a null object reference

I actually get the exact same crashed with the official Twitch app, and a quick google search brings up, that one would just have to create an empty LayoutManager for the RecyclerView to solve it, but looking at your code, you do create one in the (propably responsible?) ViewActivity. 
I fail to see where the bug might be in your code, but maybe you have an idea?

**Comment by Kennyc1012** [comment]
This is happening in the third party library [AndroidSlidingUpPanel](https://github.com/umano/AndroidSlidingUpPanel) . I have never been able to to replicate this, how did you get into this state, ie  rotating, swiping?


Full stack trace from Fabric:

```java
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$LayoutManager.canScrollVertically()' on a null object reference
       at android.support.v7.widget.RecyclerView.computeVerticalScrollRange(RecyclerView.java:1535)
       at android.view.View.awakenScrollBars(View.java:11660)
       at android.view.View.initialAwakenScrollBars(View.java:11566)
       at android.view.View.onWindowVisibilityChanged(View.java:8800)
       at android.view.View.dispatchAttachedToWindow(View.java:13550)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2688)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
       at android.view.ViewGroup.addViewInner(ViewGroup.java:3975)
       at android.view.ViewGroup.addViewInLayout(ViewGroup.java:3912)
       at android.view.ViewGroup.addViewInLayout(ViewGroup.java:3890)
       at android.support.v4.view.ViewPager.addView(ViewPager.java:1339)
       at android.view.ViewGroup.addView(ViewGroup.java:3727)
       at android.view.ViewGroup.addView(ViewGroup.java:3700)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:905)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.app.BackStackRecord.run(BackStackRecord.java:835)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
       at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:483)
       at android.support.v13.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1105)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:951)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1473)
       at android.view.View.measure(View.java:17554)
       at com.sothree.slidinguppanel.SlidingUpPanelLayout.onMeasure(SlidingUpPanelLayout.java:753)
       at android.view.View.measure(View.java:17554)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5541)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
       at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
       at android.view.View.measure(View.java:17554)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5541)
       at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:444)
       at android.view.View.measure(View.java:17554)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5541)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
       at android.view.View.measure(View.java:17554)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5541)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
       at android.view.View.measure(View.java:17554)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5541)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
       at android.view.View.measure(View.java:17554)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:550)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5286)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
```

**Comment by Crylion** [comment]
It's really just opening the app and pressing one of the posts. As it's trying to open it, I get the crash. Regardless of screen orientation or any other factor I can see. 

I guess it must be a specific combination of my phone (nexus 5), rom (a custom one) and/or OS version or something. If you can't replicate it and the Twitch guys also seem to not be fixing it, than it's propably something on my side >.<

With the twitch app I found the workaround of getting to the crashing activity directly by way of the twitch mobile site, which has a button that starts the activity for a specific stream more directly x)

**Comment by Kennyc1012** [comment]
I myself have a N6 runnnig cm12.1 (5.1.1) and haven't been able to replicate it. I'll dig through the code of the library and see if I can find the problem.

**Comment by Crylion** [comment]
One more detail: Just tried opening a imgur url from a chat with Opengur and that crashes as well, so it's not just the transition from the overview to a post.

**Comment by Kennyc1012** [comment]
Whenever you get a chance, I have two potential fixes. There seems to be a problem with the recyclerview when drawing scroll bars. [Build-A](https://drive.google.com/file/d/0B76YfpA-PixvOU9NczdKTVJOOU0/view?usp=sharing) and [Build-B](https://drive.google.com/file/d/0B76YfpA-PixvNi1RWmFtYzJIbUU/view?usp=sharing), I'm hoping that Build-A fixes the problem as it still works with scrollbars. Build-B will fix it I'm 99% sure but the scrollbars will not be shown for comments.

**Comment by Crylion** [comment]
Im terribly sorry but both builds (un- and reinstalled multiple times to make sure) still throw the same exception oO    

    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$LayoutManager.canScrollVertically()' on a null object reference
            at android.support.v7.widget.RecyclerView.computeVerticalScrollRange(RecyclerView.java:1535)
            at android.view.View.awakenScrollBars(View.java:11660)
            at android.view.View.initialAwakenScrollBars(View.java:11566)
            at android.view.View.onWindowVisibilityChanged(View.java:8800)
            at android.view.View.dispatchAttachedToWindow(View.java:13550)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2688)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
            at android.view.ViewGroup.addViewInner(ViewGroup.java:3975)
            at android.view.ViewGroup.addViewInLayout(ViewGroup.java:3912)
            at android.view.ViewGroup.addViewInLayout(ViewGroup.java:3890)
            at android.support.v4.view.ViewPager.addView(ViewPager.java:1339)
            at android.view.ViewGroup.addView(ViewGroup.java:3727)
            at android.view.ViewGroup.addView(ViewGroup.java:3700)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:905)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
            at android.app.BackStackRecord.run(BackStackRecord.java:835)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
            at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:483)
            at android.support.v13.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1105)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:951)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1473)
            at android.view.View.measure(View.java:17554)
            at com.sothree.slidinguppanel.SlidingUpPanelLayout.onMeasure(SlidingUpPanelLayout.java:753)
            at android.view.View.measure(View.java:17554)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5541)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
            at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
            at android.view.View.measure(View.java:17554)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5541)
            at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:444)
            at android.view.View.measure(View.java:17554)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5541)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
            at android.view.View.measure(View.java:17554)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5541)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
            at android.view.View.measure(View.java:17554)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5541)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
            at android.view.View.measure(View.java:17554)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.jav

**Comment by Kennyc1012** [comment]
Okay, try [Build-C](https://drive.google.com/file/d/0B76YfpA-Pixvbk5pN3lIWUpKYzA/view?usp=sharing). If this doesn't work, then I am all out of ideas :/

**Comment by Crylion** [comment]
Still no luck :( but at least a slightly different location for the exception 

    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$LayoutManager.canScrollVertically()' on a null object reference
            at android.support.v7.widget.RecyclerView.computeVerticalScrollOffset(RecyclerView.java:1494)
            at android.view.View.awakenScrollBars(View.java:11660)
            at android.view.View.initialAwakenScrollBars(View.java:11566)
            at android.view.View.onWindowVisibilityChanged(View.java:8800)
            at android.view.View.dispatchAttachedToWindow(View.java:13550)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2688)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
            at android.view.ViewGroup.addViewInner(ViewGroup.java:3975)
            at android.view.ViewGroup.addViewInLayout(ViewGroup.java:3912)
            at android.view.ViewGroup.addViewInLayout(ViewGroup.java:3890)
            at android.support.v4.view.ViewPager.addView(ViewPager.java:1339)
            at android.view.ViewGroup.addView(ViewGroup.java:3727)
            at android.view.ViewGroup.addView(ViewGroup.java:3700)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:905)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
            at android.app.BackStackRecord.run(BackStackRecord.java:835)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
            at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:483)
            at android.support.v13.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1105)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:951)
            at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1473)
            at android.view.View.measure(View.java:17554)
            at com.sothree.slidinguppanel.SlidingUpPanelLayout.onMeasure(SlidingUpPanelLayout.java:753)
            at android.view.View.measure(View.java:17554)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5541)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
            at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
            at android.view.View.measure(View.java:17554)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5541)
            at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:444)
            at android.view.View.measure(View.java:17554)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5541)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
            at android.view.View.measure(View.java:17554)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5541)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
            at android.view.View.measure(View.java:17554)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5541)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
            at android.view.View.measure(View.java:17554)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.j

**Comment by Kennyc1012** [comment]
Last attempt, if [Build-D](https://drive.google.com/file/d/0B76YfpA-PixvemxqLXlCeEcxUkE/view?usp=sharing) doesn't work, than I am sorry, but I have no clue on how to fix this and since you are the only user experiencing this, I am going to pass on it. 

<img width="976" alt="screen shot 2015-07-12 at 7 18 10 am" src="https://cloud.githubusercontent.com/assets/2333025/8637573/696356ee-2866-11e5-8925-8966ed4ec835.png">

**Comment by Crylion** [comment]
I was worrying that might be the case x) I have no idea why my system has a problem with that xD Build D throws the earlier exception again x) sorry to have stressed you with this, I know how taxing such a bug hunt can be. I'll try to figure out what the reason for this is and tell you about it if I find anything ^^
Thanks for your effort!

**Comment by Jawnnypoo** [comment]
I think AndroidSlidingUpPanel is not the issue, it just happens to be in the stack trace. From what I can tell from a bit of Googling, the problem has to do with a RecyclerView not having a LayoutManager associated with it. Since the stack trace doesn't really point anywhere, maybe just look around and see if there is anywhere where a RecyclerView does not set its layout manager in the onCreate/onCreateView method?

**Comment by Kennyc1012** [comment]
As you can see [here](https://github.com/Kennyc1012/Opengur/blob/master/src/main/java/com/kenny/openimgur/activities/ViewActivity.java#L207), the layout manager is set as soon as the view is set, that is the earliest it can be set without the recyclerview being NULL. The easy fix is just disabling scrollbars for the comments, but I rather not do that since its nice knowing how long they are. My guess at what is happening is when the view is being inflated, onMeasure is being called before the layout manager is being set which is why this is happening. I'm leaning towards this has to be some issue with whatever rom you are running as there are only (now) two users who are experiencing this crash, both on a 5.1.1 device (N5 and N6) with a root device. @Crylion What rom are you currently running, if any.

**Comment by Crylion** [comment]
I had the problem with OptiPop, but switched to Cataclysm a few days ago. Now the problem is gone and the normal Opengur version from the play store works again.

**Comment by Kennyc1012** [comment]
Okay, then I am going to close this as that is likely the issue.
